### ISSUE TITLE
Make tags clickable

### ISSUE THREAD

**Issue by arirawr** [EmbarkStudios/opensource-website#1]
Users should be able to click tags anywhere they appear and be taken to a filtered view of all projects with that tag.

**Comment by hairarrow** [comment]
Hey @arirawr,

This sounds like something I'd be able to handle.

A couple of questions:

- Would clicking on a tag navigate to a new view or scroll to an anchor on the page?
- Do you have anything specific in mind for the tag's hover interaction?

**Comment by pidwid** [comment]
ill work on this issue tell me where to redirect on clicking tags.

**Comment by arirawr** [comment]
Hey @pidwid, someone has already started working on this in #10 !

**Comment by arirawr** [comment]
Resolved by #10 🎉
