### ISSUE TITLE
Description for `octobors` project disappears

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/opensource-website#107]
This is quite odd, the description for the `octobors` project is not visible neither on Firefox or Chrome:

![image](https://user-images.githubusercontent.com/1262692/150194399-4416b1fb-9fdf-4ab1-99c1-bfb7007cdb8a.png)

It is defined in https://github.com/EmbarkStudios/opensource-website/blob/main/static/data/data.json, and even more odd: if you refresh the browser you will briefly see it until it disappears!

There are some other oddities with the site just after refresh also

**Comment by Nisatru** [comment]
Hi,
that's a good catch.

Currently the site works as following.
When building the static site while deploying zola takes the data from the `data.json` file you linked and inserts values like the project description for the cards in your screenshot.

To get the current values for github stars, issues count and project description JavaScript code will fetch this data from the GitHub API and insert the values if given.


Now in the case of octobors there is a description in the `data.json` file and thats why you see the description briefly when you load the site.
The GitHub API returns `null` for the octobors description so the JavaScript code will update the description with an empty one.
Thats unwanted behaviour tho.
You can see my updates in the linked PR #110  where I disabled updating the project description if the GitHub API returns `null` for it.


Maybe this explanation of how the site's content gets updated relating to the GitHub API response also shines some light on the other oddities you recognized or did you also observe some other weird behaviour?
We can think about not updating the description via JavaScript at all and keeping the static descriptions that are written in the `data.json` file.
