### ISSUE TITLE
Move hosting of site to GitHub pages or Google

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/opensource-website#108]
We currently use Netlify to deploy this page at https://embark.dev, netlify is great and has a fantastic preview action in the PRs that is super useful. 

But this is also only 1 of 2 sites we have that use Netlify, so would be nice to consolidate and use fewer external services, this is a static web page so maybe easiest would be to just use GitHub Pages for this? 

Maybe there is a good way with that also to get preview links in CI for PRs also?

cc @celialewis3 @fredrikatembark

**Comment by repi** [comment]
We should do this in now before March, talked to @vojd about it

**Comment by vojd** [comment]
Last March is the date I've heard and we'll make sure it's handled in good time before

**Comment by vojd** [comment]
Closed in https://github.com/EmbarkStudios/opensource-website/pull/112
