### ISSUE TITLE
Link to site from embark-studios.com

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/opensource-website#111]
Right now we don't have a link to this site on https://embark-studios.com to https://embark.dev, we should have something. like a "developers" link? either in the top menu bar or at least somewhere small on the bottom.

talked to @celialewis3 about adding it a recently

**Comment by celialewis3** [comment]
Done! New link in the navbar for "Open Source" (https://www.embark-studios.com/)
![image](https://user-images.githubusercontent.com/48493789/155696657-b4fc83a8-5085-4ade-b105-32ab70afb64a.png)

**Comment by repi** [comment]
Nice!
