### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by arirawr** [EmbarkStudios/opensource-website#2]
Users should be able to search through projects by name, tag, or description.

**Comment by pepas24** [comment]
Hi, I want to make this feature, where do you think should be the input for search? In the "A-Z" section?

**Comment by arirawr** [comment]
Hey @pepas24 ! Glad to hear you're interested.

There's a couple options for this. I think A-Z is a good start, and the A-Z table would filter on the results. Something to keep in mind is that we'd want to make the descriptions also searchable. 

The alternative is a global search in the header, but we'd need some kind of modal/overlay for that (something like [this](https://developer.spotify.com/?query=javascript))

**Comment by arirawr** [comment]
Thanks to @pepas24 for implementing this in #12!
