### ISSUE TITLE
Abstract shared layouts into components

### ISSUE THREAD

**Issue by arirawr** [EmbarkStudios/opensource-website#22]
**Describe the solution you'd like**
Shared layouts (head, header, footer, etc) should be turned into Vue components and shared between pages.

**Describe alternatives you've considered**
Currently just copy-pasting - this does not scale.

**Comment by celialewis3** [comment]
Since we are moving towards creating a static site with a site generator like Zola or Hugo instead Vue, this issue is now obsolete. The current relevant issue can be found at #87.
