### ISSUE TITLE
Create a nice view for newsletter archives and signup

### ISSUE THREAD

**Issue by arirawr** [EmbarkStudios/opensource-website#23]
**Describe the solution you'd like**
Currently, the newsletter is displayed as a basic HTML list on the homepage. We should have a separate page (embark.dev/newsletter) that shows recent newsletters in a nice way, and allows users to sign up. (this is currently done through the basic mailchimp page)

**Comment by soniasingla** [comment]
This issue has been resolved with PR #69 🤓
