### ISSUE TITLE
Design a view for upcoming events/meetups

### ISSUE THREAD

**Issue by arirawr** [EmbarkStudios/opensource-website#29]
It would be cool to have a view for meetups or conferences we're hosting or attending. This could be a section on the homepage that links out to a full calendar view.

This would be fed by a .json data source, similar to projects. The data structure would probably look like this:

```json
{
    "title": "Blender 3D Meetup Stockholm",
    "date": "2020-02-03T18:00:00",
    "location_city": "Stockholm",
    "location_country_code": "SE",
    "signup_link": "https://beep.boop"
}
```

**Comment by hipstermojo** [comment]
Hi, I'd like to take this issue.

**Comment by arirawr** [comment]
Please submit a PR when you're ready :)

**Comment by Octateam** [comment]
Hello, would like to work on this

**Comment by arirawr** [comment]
Cool! Submit a PR when you're ready, or feel free to post design ideas here :)

**Comment by Octateam** [comment]
Here's is something i came up with
![Screenshot (39)](https://user-images.githubusercontent.com/30428398/94962868-16bb4a80-04ef-11eb-85af-6a3a8627dafa.png)

**Comment by Octateam** [comment]
what do you think @arirawr

**Comment by Rihanat** [comment]
@arirawr can I work on this?

**Comment by arirawr** [comment]
That looks nice @Octateam !

Since the website has dark and light mode (based on the user's computer setting), I'd like to see what it looks like in darker colours as well. I think it also may be nicer with the content (date/time/location) and CTA button left-justified.

@Rihanat I'm happy for anyone to work on this, just submit a PR when you're ready. Be aware that there are multiple folks working on this (which is totally fine!) so we may need to do some merging/coordination later on.

**Comment by Octateam** [comment]
Thanks @arirawr Can I see what the current dark mode looks like so I don’t go using a different color tone for it. A screenshot would do, I’ll pick the color from there

**Comment by arirawr** [comment]
You can use your computer's dark mode preferences to change the site theme :)

**Comment by Octateam** [comment]
So I looked at the website and came up with these little changes. Hope these work better now @arirawr 


![Screenshot (43)](https://user-images.githubusercontent.com/30428398/95221183-153f9a00-07ef-11eb-837d-a95e210fa4ca.png)
![Screenshot (44)](https://user-images.githubusercontent.com/30428398/95221193-17095d80-07ef-11eb-99bf-b3c7bf712b09.png)

**Comment by arirawr** [comment]
Looks nice! Do you want to take stab at implementing it or let one of the other folks who commented here try?

**Comment by Octateam** [comment]
I think I’ll let someone else have a go at it, I don’t really write code 😅

**Comment by arirawr** [comment]
Thanks so much for the contribution then! @hipstermojo @Rihanat please see screenshots above for design reference :)

**Comment by Octateam** [comment]
Thanks for letting me contribute, really hope it’s implemented 😅🤞🏽

**Comment by xterpride** [comment]
> Looks nice! Do you want to take stab at implementing it or let one of the other folks who commented here try?

hey, what type of code would i need to learn to do this?

**Comment by xterpride** [comment]
@arirawr

**Comment by repi** [comment]
sorry this is a really old issue that we had forgotten to close
