### ISSUE TITLE
Add mergify

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/opensource-website#50]
So we approved PRs get automerged and deployed automatically, like we have for our other open source sites

**Comment by lpil** [comment]
@repi Do we want this config from the Ark repo? https://github.com/EmbarkStudios/ark/tree/main/.github/workflows

If so shall I also add this to to the opensource-template and the other repos that lack this?

**Comment by repi** [comment]
Nope that is internal action, and not https://mergify.io/ which we use for our public open source repos

**Comment by lpil** [comment]
Ah, thanks!
