### ISSUE TITLE
Merge duplicate sections for enhanced view

### ISSUE THREAD

**Issue by soniasingla** [EmbarkStudios/opensource-website#52]
The projects under section `Projects A-Z` is repetitive with the projects under sections:
> Our rust projects
> Our go projects
> Our web projects

We should merge the projects under one section to remove duplicity, and include more tags (:

**Comment by soniasingla** [comment]
Over to @arirawr !

**Comment by arirawr** [comment]
Makes sense to me - what would you propose as sections?

Having Rust and other languages is valuable because we can then link to a specific section. There are also individual pages for tags if you click on a tag.

**Comment by soniasingla** [comment]
We can remove the section, `Projects A-Z` as the projects under A-Z are already covered above. WDYT?

**Comment by lpil** [comment]
The language sections don't contain all the projects so we'd lose some without the A-Z. Perhaps an "other" section could contain those.

**Comment by soniasingla** [comment]
Only 2-3 projects are there which are not included in the above section, before merging, I will add those in the above sections, we won't loose anything :)

**Comment by lpil** [comment]
We could probably put the GKE one in web but I don't think the Docker one fits there or in Rust or Go. Could have a containerisation category but seems like it would stay pretty sparse forever.

**Comment by arirawr** [comment]
I like having a definitive list of "all", as we will add more that don't fit. Think blender, unreal, k8s, angelscript, backend. Those sections may only have 1-2 things.

Design-wise, what if we just collapse the A-Z by default? A "see all projects" type thing.

**Comment by lpil** [comment]
I like the idea of collapsing it by default a bunch :)

**Comment by soniasingla** [comment]
This issue has been fixed with PR #60
