### ISSUE TITLE
Discord - Primary Option for Contributors

### ISSUE THREAD

**Issue by soniasingla** [EmbarkStudios/opensource-website#53]
Mention Discord clearly as primary option under `Want to get involved? ` and also, [here](https://github.com/EmbarkStudios/opensource-website/blob/main/CONTRIBUTING.md)?

Right now, we have the Discord tiny icon in the top which appears to be hidden (:

**Comment by arirawr** [comment]
Yep - we should definitely have a section for discord, or include it in the getting involved section!

**Comment by soniasingla** [comment]
Fixed with PR #57
