### ISSUE TITLE
Handle pagination of GitHub repo API

### ISSUE THREAD

**Issue by lpil** [EmbarkStudios/opensource-website#74]
https://github.com/EmbarkStudios/opensource-website/blob/0e19bc819011a9fd6d8fb810551cfe964f9d20fb/script.js#L115-L117

Here we make a call to the GitHub API to get the first 100 repos from our org. At time of writing we have 164 public repos, so this query does not get them all, so we miss some data. Handling the API pagination resolves this problem.

This could also be a nice opportunity to break the `mounted` function of the Vue app into multiple functions, it is a little large at present.

**Comment by XAMPPRocky** [comment]
This is supported in octokit out of the box. https://octokit.github.io/rest.js/v18#pagination

```js
const issues = octokit.iterator(octokit.repos.listForOrg, {
    org: "EmbarkStudios",
})

for await (const issue of issues) {
  // do whatever you want with each issue, break out of the loop, etc.
}
```
